version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: deploy/src/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

volumes:
  postgres: